// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

import { explicitSslDatabaseUrl } from "./lib/database-url";

const rawUrl = process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: explicitSslDatabaseUrl(rawUrl) ?? rawUrl,
  },
});
